### ISSUE TITLE
Not all tests completed successfully

### ISSUE THREAD

**Issue by isopen** [ton-blockchain/multisig-contract-v2#10]
![image](https://github.com/ton-blockchain/multisig-contract-v2/assets/7373292/30cd6572-3e7b-476e-b67e-7307c87a8520)
Now it’s unclear why this was done, but ok.
Looks like this test just doesn't work.
`should not deploy with threshold = 0`
![image](https://github.com/ton-blockchain/multisig-contract-v2/assets/7373292/c2870b3a-3994-4d27-9333-55ec4fe57e4f)

![image](https://github.com/ton-blockchain/multisig-contract-v2/assets/7373292/1965d874-9cf2-4be5-9b09-b88575875a01)

**Comment by tolya-yanot** [comment]
just skipped not actual unit-test
