### ISSUE TITLE
no limit action order !

### ISSUE THREAD

**Issue by mahdihoseini123** [ton-blockchain/multisig-contract-v2#13]
(Multisig does not limit the content of Order actions, so an Order can contain absolutely any action, including those that create new multisig orders or validate existing multisig orders or change the multisig configuration (eg, a list of signers).)

Isn't this action wrong!?
What if someone keeps passing order zero!?
And repeat this action over and over again!?

**Comment by mahdihoseini123** [comment]
Since audit numbers below 1 can be very close to 0
And they are not much different from 0
It is better to put 1 instead of 0.
Line 42 and 188 (multisig-contract-v2/contracts
/multisig.func)
throw_unless(error::invalid_threshold, threshold > 0);

**Comment by mahdihoseini123** [comment]
next_order_seqno += 1;
Create a mechanism that throws an error if it is greater than 1
Line 114 (contracts/multisig.func)

**Comment by mahdihoseini123** [comment]
I think that since there is no limit for simultaneous sending, it can cause problems for multisig.func
For example, you send 100 simultaneous requests when you send them together
And your request should be more than your wallet assets
Wallet assets are not considered
So it is better in line 114 of multisig.func
Instead
next_order_seqno += 1;
be placed
next_order_seqno = 1;
To avoid simultaneous sending of order requests
thank you

**Comment by mahdihoseini123** [comment]
Each wallet can only send 2 orders before being placed in multisig

// Define the Wallet structure
struct Wallet {
  int address;
  int ordersSent;
  bool isMultisigRequired;
};

// Function to send an order
Wallet sendOrder(Wallet wallet) {
  if (wallet.isMultisigRequired) {
    prints("Multisig is required for this wallet.\n");
    return wallet;
  } else {
    int updatedOrdersSent = wallet.ordersSent + 1;
    bool updatedIsMultisigRequired = updatedOrdersSent >= 2;
    return Wallet(wallet.address, updatedOrdersSent, updatedIsMultisigRequired);
  }
}

// Example usage
var Wallet myWallet = {address: 0x123, ordersSent: 0, isMultisigRequired: false};
myWallet = sendOrder(myWallet); // First order sent
myWallet = sendOrder(myWallet); // Second order sent, multisig will be required next

ton addres : UQB4qLu_J96LcFjM5ppPGO0XoDeLLTa99V4KBiOu6uUrClZG

**Comment by tolya-yanot** [comment]
It doesn't make any sense, ban
