### ISSUE TITLE
Transaksi nyaman hanya di sini

### ISSUE THREAD

**Issue by Inrawi** [ton-blockchain/multisig-contract-v2#21]
Melakukan transaksi mata uang dengan mudah, tanpa harus repot ganti aplikasi untuk mencairkan menjadi saldo dan keamanan yg terjamin
![IMG-20240406-WA0084](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/e7cc5c51-8c03-4024-908d-5f872500eb5c)
![IMG-20240406-WA0072](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/cb77a8fd-9517-4a4f-a349-08697d13bf18)
![IMG-20240406-WA0065](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/2a7978af-aa87-49e8-b30f-523b6181b379)
![IMG-20240406-WA0040](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/77ca7f45-1369-4984-ac65-2f462304f885)
![IMG-20240405-WA0246](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/c53fc30a-dfdc-4dca-b22a-8aa21a1b9b13)
![IMG-20240406-WA0001](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/d3f57493-219e-4fb7-b574-c83898229ecb)
![IMG-20240405-WA0205](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/8529f52f-4ae3-4bb1-97a5-0bb5efd8504b)
![IMG-20240405-WA0207](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/2855c330-db4e-4077-8a0f-67c9228dabc6)
![IMG-20240405-WA0206](https://github.com/ton-blockchain/multisig-contract-v2/assets/166182292/039a9eba-cb9c-42a6-aa10-500113368016)
### @Bganteng77

**Comment by tolya-yanot** [comment]
offtopic, ban
