### ISSUE TITLE
The transfer fee on the TON Coin network could be lower.

### ISSUE THREAD

**Issue by hpiri** [ton-blockchain/multisig-contract-v2#26]
pragma solidity ^0.8.0;

contract Toncoin {
    address public owner; // Owner of the contract
    uint256 public sellerFeePercentage; // Fee percentage for sellers
    uint256 public buyerFeePercentage; // Fee percentage for buyers

    constructor() {
        owner = msg.sender; // Set the contract creator as the owner
        sellerFeePercentage = 1; // Initial fee percentage for sellers
        buyerFeePercentage = 0; // Initial fee percentage for buyers (no fee)
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can update fees");
        _;
    }

    function setSellerFeePercentage(uint256 _newFee) external onlyOwner {
        sellerFeePercentage = _newFee;
    }

    function setBuyerFeePercentage(uint256 _newFee) external onlyOwner {
        buyerFeePercentage = _newFee;
    }

    // Other contract functions...
}

https://t.me/hp_473

**Comment by hpiri** [comment]
https://t.me/hp_473

**Comment by ProgramCrafter** [comment]
Completely irrelevant to contract to be tested.

**Comment by tolya-yanot** [comment]
offtopic, ban
