### ISSUE TITLE
Review and Enhance Approval Mechanism

### ISSUE THREAD

**Issue by iprocode** [ton-blockchain/multisig-contract-v2#34]
Upon my examination of the `recv_internal` function in the "multisig.func" file, I found potential security risks in the approval mechanism of the Multisig smart contract. However, further analysis is required to ascertain the extent of these risks. Below are the key findings and possible solutions for improvement:

1. **Inadequate Approval Validation:**
    * **Issue:** The condition `(approvals_num >= threshold)`, (line 166) allows for executions even when the number of approvals exceeds the required threshold. This leniency could lead to unauthorized executions if additional signers approve the order beyond the required threshold.

    * **Possible solution:** Update the condition to `(approvals_num == threshold)` to ensure that only the exact number of required approvals triggers execution. This stricter validation will mitigate the risk of unauthorized executions caused by surplus approvals.
 
2. **Expiration Date Verification:**
    * **Issue:** The current implementation checks if the `expiration_date`, (line 167) is greater than or equal to the current time (`now()`). However, this check does not enforce a specific timeframe within which the order must be executed, potentially allowing for delayed executions beyond the intended expiration window.

    * **Possible solution:** Implement a stricter expiration date verification mechanism by specifying a maximum allowable timeframe for execution from the order's initialization. The condition could be updated to: 
`throw_unless(error::expired, expiration_date >= now() & expiration_date - now() <= MAX_EXPIRATION_TIME);`
This enhancement will prevent delayed executions and ensure timely execution within the designated expiration period.

I hope the provided insights and suggestions are helpful and contribute to the improvement of the contract's functionality.

Best regards!

**Comment by tolya-yanot** [comment]
We don't see any problem in the above cases
