### ISSUE TITLE
Possible incorrect estimation if time is expired

### ISSUE THREAD

**Issue by SubFactorial** [ton-blockchain/multisig-contract-v2#44]
In multisig.func in lines: 193-196 there are following code:
int get_order_estimate(cell order, int expiration_date) method_id {
    (_, _, cell signers, _, _, _) = load_data();
    return calculate_order_processing_cost(order, signers, expiration_date - now());
}

If time is expired then duration will be negative and it is possible that estimation will be calculated incorrectly.

**Comment by tolya-yanot** [comment]
get_storage_fee with negative duration will throw error
