### ISSUE TITLE
Order might not be executed in some cases

### ISSUE THREAD

**Issue by SubFactorial** [ton-blockchain/multisig-contract-v2#45]
In order.func in line 110 there is following check:
if (approvals_num == threshold)
then send_message_with_only_body is called and after that 
sent_for_execution? = true;

If by some reason send_message_with_only_body will throw exception and after that new signer try to approve order then order will not be executed, because approvals_num > threshold.

**Comment by tolya-yanot** [comment]
if send_message_with_only_body will throw exception then no changes will be in order smart contract data
